name: Build App on Heroku
on:
  push:
    branches:
      - main

jobs:
  heroku-pull-request:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: acebook-zark-muckerberg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          justlogin: true
          
      - name: Add Heroku remote
        run: git remote add acebook ${{ secrets.HEROKU_REMOTE }}

      - name: Push to master branch app on Heroku
        run: git push acebook main